# Generated by Django 4.2.4 on 2024-09-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_jobmodel_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymodel',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview_scheduled', 'Interview Scheduled'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=20),
        ),
    ]
