# Generated by Django 4.2.4 on 2024-09-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_alter_jobapplymodel_status_userprofile_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageModel',
        ),
    ]
